name: amazon_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    
  fonts:

    - family: AmazonEmber
      fonts:
        - asset: assets/fonts/Ember/AmazonEmber_Th.ttf
          weight: 100
        - asset: assets/fonts/Ember/AmazonEmber_ThIt.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Ember/AmazonEmber_Lt.ttf
          weight: 300
        - asset: assets/fonts/Ember/AmazonEmber_LtIt.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Ember/AmazonEmber_Rg.ttf
          weight: 400
        - asset: assets/fonts/Ember/AmazonEmber_RgIt.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Ember/Amazon-Ember-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ember/Amazon-Ember-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Ember/AmazonEmber_Bd.ttf
          weight: 700
        - asset: assets/fonts/Ember/AmazonEmber_BdIt.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Ember/AmazonEmber_He.ttf
          weight: 900
        - asset: assets/fonts/Ember/AmazonEmber_HeIt.ttf
          weight: 900
          style: italic
